name = "pet-store"
main = "index.html"
compatibility_date = "2024-08-19"

[env.production]
route = "pet-store.YOUR_DOMAIN.com"

[[env.production.rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = false