apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pet-store-landing-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: pet-store-landing.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pet-store-landing-service
            port:
              number: 80